# Site settings
title: Joe's Blog
header-img: img/home-bg.jpg
email: sjhoung@gmail.com
description: "A Software Engineers Blog"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: 
github_username:  houngj
facebook_username:  

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
